Make accessFilter file registration thread safe
graalvm/native-build-tools pull request #635
Opened 2024-10-31 15:09 UTC by dnestoro

This PR should fix https://github.com/graalvm/native-build-tools/issues/626

Described issue probably occurs in multi-threaded environment because the reported error throws `FileAlreadyExistsException`  even though [we checked first that file doesn't exist](https://github.com/graalvm/native-build-tools/blob/master/common/utils/src/main/java/org/graalvm/buildtools/agent/AgentConfiguration.java#L155). 

As per documentation of `java.nio.file.Files#createDirectory`:
> Creates a new directory. The check for the existence of the file and the creation of the directory if it does not exist are a single operation that is atomic with respect to all other filesystem activities that might affect the directory

Since we only care that directory with the given name exists, we can just catch and ignore `FileAlreadyExistsException` in this case.

2024-11-04 13:49 UTC, melix requested changes

2024-11-04 13:49 UTC, melix commented on common/utils/src/main/java/org/graalvm/buildtools/agent/AgentConfiguration.java
> +        String accessFilterPrefix = "access-filter";
:x: Should these be constants?

2024-11-04 13:49 UTC, melix commented on common/utils/src/main/java/org/graalvm/buildtools/agent/AgentConfiguration.java
> +                System.out.println("Access-filter file already exists. Delete temporary one.");
:x: Either use a logger or remove the debug statement.

2024-11-04 15:55 UTC, olpaw commented on common/utils/src/main/java/org/graalvm/buildtools/agent/AgentConfiguration.java
> +                 tmpAccessFilter = Files.createTempFile(agentDir, ACCESS_FILTER_PREFIX, ACCESS_FILTER_SUFFIX);
indentation is not aligned

2024-11-04 16:17 UTC, olpaw commented on common/utils/src/main/java/org/graalvm/buildtools/agent/AgentConfiguration.java
> +                 tmpAccessFilter = Files.createTempFile(agentDir, ACCESS_FILTER_PREFIX, ACCESS_FILTER_SUFFIX);
You mentioned that his gave you:
```
Caused by: java.nio.file.FileAlreadyExistsException: /tmp/agent-config/access-filter21830177911714255.json
```
Why is this not an issue anymore?

2024-11-04 16:22 UTC, olpaw requested changes

2024-11-04 16:22 UTC, olpaw commented on common/utils/src/main/java/org/graalvm/buildtools/agent/AgentConfiguration.java
> +                 tmpAccessFilter = Files.createTempFile(agentDir, ACCESS_FILTER_PREFIX, ACCESS_FILTER_SUFFIX);
Maybe it's better to create the temp name differently. A combination of PID + UTC timestamp would be good.

2024-11-05 14:00 UTC, olpaw commented on common/utils/src/main/java/org/graalvm/buildtools/agent/AgentConfiguration.java
> +            Path tmpAccessFilter = agentDir.resolve(ACCESS_FILTER_PREFIX + pid + time + ACCESS_FILTER_SUFFIX);
```suggestion
            Path tmpAccessFilter = agentDir.resolve(ACCESS_FILTER_PREFIX + '_' + pid  + '_' + time  + '_' + ACCESS_FILTER_SUFFIX);
```

2024-11-12 13:14 UTC, olpaw submitted a review, later dismissed
- [x]  Adjust the logging and error messages before merging.

2024-11-12 15:20 UTC, melix approved these changes

2024-11-12 15:21 UTC, merged